# Generated by Django 4.0.5 on 2022-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_designer_average_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='stars',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='average_stars',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
