# Generated by Django 4.0.5 on 2022-06-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
