# Generated by Django 4.0.5 on 2022-06-04 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerpopol',
            name='designer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.designer'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.designerpopol'),
        ),
    ]
