# Generated by Django 4.0.5 on 2022-06-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerpopol',
            name='designer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.designer'),
        ),
    ]
